### ISSUE TITLE
stupid question about squid and apache2 ^^

### ISSUE THREAD

**Issue by ghost** [salrashid123/squid_proxy#13]
H i @salrashid123 ,

Hope you are all well !

I am sorry about this question but I still do not get how to cache html results from a website hosted by an apache2 server.

Do you mind 1-2 minutes of your precious time to share some insights or inputs on that ?

Thanks in advance as I am a little bit lost on this one.

Cheers,
Luc Michalski

**Comment by salrashid123** [comment]
hey, is the apache server using https by chance?   you can't really cache encrypted traffic since it'd be opaque to the proxy (unless you intercept the tls).  if ust http, i'm sure you've seen [this example](https://github.com/salrashid123/squid_proxy#cache)
