### ISSUE TITLE
provided CA_cert.pem untrusted - missing signing CA cert?

### ISSUE THREAD

**Issue by imanassypov** [salrashid123/squid_proxy#14]
Hi team, 

I am having troubles with testing the SSL intercept option with the provided CA_cert.pem file. 

Is there a parent signing authority chain that I need reference in conjunction with this cert - what CA was used to sign it?

If I revert to self-signed CA cert, everything works fine. So I suspect I may be missing some intermediate/root ca certs if I am to leverage the supplied CA_cert.pem.

Thank you very much,
-igor

**Comment by salrashid123** [comment]
`CA_crt.pem` is actually a subordinate CA...which was signed by this
  https://github.com/salrashid123/squid_proxy/blob/master/root-ca.crt

fwiw you can also gen the full chain (root+sub) here https://github.com/salrashid123/ca_scratchpad
