### ISSUE TITLE
How regen CA using keyUsage

### ISSUE THREAD

**Issue by deploy-yogo** [salrashid123/squid_proxy#5]
Hello,

I just saw that you generate new CA
can i get the command used

?

**Comment by salrashid123** [comment]
you need to set the keyUsage in the openss.cnf while generating it , eg

create openssl.cnf in a folder ('myCA') from here:
 -  https://gist.github.com/salrashid123/dbb032d4538c9df5d5ceed3f3e160ed4

then
```
mkdir myCA
cd myCA
mkdir new_certs
touch index.txt
echo 00 > serial
```

generate the CA:

```
openssl genrsa -out CA_key.pem 2048
openssl req -x509 -days 600 -new -nodes -key CA_key.pem -out CA_crt.pem -extensions v3_ca -config openssl.cnf    -subj "/C=US/ST=California/L=Mountain View/O=Google/OU=Enterprise/CN=MyCA"
```

> note the -extension v3_ca i used and look for that in ```openssl.cnf```

verify
```
openssl x509 -in CA_crt.pem -text -noout
```

```
        X509v3 extensions:
            X509v3 Basic Constraints: 
                CA:TRUE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment, Data Encipherment, Key Agreement, Certificate Sign, CRL Sign
```

---

generate a server cert

```
openssl genrsa -out server.key 2048
openssl req -config openssl.cnf -days 400 -out server.csr -key server.key -new -sha256  -extensions v3_req  -subj "/C=US/ST=California/L=Mountain View/O=Google/OU=Enterprise/CN=squid.yourdomain.com"
openssl ca -config openssl.cnf -days 400 -notext  -in server.csr   -out server.crt
```

> note the -extension v3_req i used and look for that in ```openssl.cnf```

verify
```
openssl x509 -in server.crt -text -noout
```

```
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, ST = California, L = Mountain View, O = Google, OU = Enterprise, CN = MyCA
        Validity
            Not Before: May 22 14:27:15 2018 GMT
            Not After : Jun 26 14:27:15 2019 GMT
        Subject: C = US, ST = California, O = Google, OU = Enterprise, CN = squid.yourdomain.com
        X509v3 extensions:
            Netscape Comment: 
                OpenSSL Generated Certificate
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
```


you'll want to carefully review what the extensions do...i just got lazy and enabled all of them since this is just a test system..

**Comment by deploy-yogo** [comment]
Thanks , else can we do this without using openssl.cnf ? 
same as before

**Comment by salrashid123** [comment]
@deploy-yogo 
that i'm not sure;  its purely an openssl thing.

**Comment by deploy-yogo** [comment]
Because i saw https://wiki.squid-cache.org/Features/DynamicSslCert and i am not sure it's that what we need to still decrypt traffic

**Comment by salrashid123** [comment]
i'm not sure i understand, the ssl_bump mode is in this repo [here](https://github.com/salrashid123/squid_proxy#https-intercept)  so atleast the behavior of what is in the link yo uprovided is already happening (i.,e the CA on the proxy _is_ generating a server_cert on the fly).  If you're asking what the minimal set of ```keyUsage=``` that i don't know; i think you need several including ```Certificate Sign```

**Comment by deploy-yogo** [comment]
Cool thanks :+1:

**Comment by deploy-yogo** [comment]
Last question , file will be used as in your project :

- server.key server.crt (for squid config)
- CA_crt.pem(for browser)
?

**Comment by salrashid123** [comment]
it shoudl be just the ```CA_crt.pem```  

```
$ wget https://raw.githubusercontent.com/salrashid123/squid_proxy/master/CA_crt.pem

$ curl -v --cacert CA_crt.pem -x localhost:3128  https://www.yahoo.com
```

(i.,e i do't get a cert warning with curl while i'm using just the ```CA_crt.pem```

**Comment by deploy-yogo** [comment]
i see on your project : 
https://github.com/salrashid123/squid_proxy/blob/master/content_adaptation/squid.conf.https_proxy

`http_port 3128 ssl-bump generate-host-certificates=on cert=/apps/server_crt.pem key=/apps/server_key.pem sslflags=DONT_VERIFY_PEER`

which dont use only CA_crt.pem as you said
