### ISSUE TITLE
Unable to run on OpenShift

### ISSUE THREAD

**Issue by saharshsingh** [salrashid123/squid_proxy#8]
Hi there,

I am unable to run this image as-is on OpenShift due to security related limitations. By default, OpenShift assigns its containers a random user ID at runtime. Since the files under /apps are owned by nobody (uid=65534) and are not globally writable, the container dies quickly after start up due to not being able to write to logs and cache locations. There are ways around it by configuring the pod to run with elevated permissions (covered in detail [here](https://www.openshift.com/blog/a-guide-to-openshift-and-uids)), but this is frowned upon in production for security reasons. 

This can be tested with docker by running `docker run --user=1000 <remaining args..>`. I was able to fix this issue for myself by writing the following simple Dockerfile:

```
FROM docker.io/salrashid123/squidproxy

RUN chmod -R 777 /apps/squid/var
```

Is this project interested in making this change directly to the original Dockerfile?

**Comment by saharshsingh** [comment]
Looks like a PR has been opened to address this: https://github.com/salrashid123/squid_proxy/pull/9

**Comment by salrashid123** [comment]
@mike-ensor   Thanks!

just merged and push to dockerhub as digest

```
$ docker push docker.io/salrashid123/squidproxy 
latest: digest: sha256:5f50ac4dba3ccbf80747574341368ef78edbea648b02805a30b893385eb78038 size: 3049
```

**Comment by saharshsingh** [comment]
Confirmed the issue is resolved with the latest image.
